allowBuilds:
  "@depot/cli": true
  esbuild: true
  sharp: true
  supabase: true
  unrs-resolver: true
autoInstallPeers: false
engineStrict: true
overrides:
  engine.io: 6.6.7
  fast-uri: 3.1.4
  postcss: 8.5.19
  sharp: 0.35.0
  tar: 7.5.20
  ws: 8.21.1
resolutionMode: highest
saveExact: true
strictPeerDependencies: true
minimumReleaseAgeExclude:
  - "@tailwindcss/node@4.3.3"
  - "@tailwindcss/oxide-android-arm64@4.3.3"
  - "@tailwindcss/oxide-darwin-arm64@4.3.3"
  - "@tailwindcss/oxide-darwin-x64@4.3.3"
  - "@tailwindcss/oxide-freebsd-x64@4.3.3"
  - "@tailwindcss/oxide-linux-arm-gnueabihf@4.3.3"
  - "@tailwindcss/oxide-linux-arm64-gnu@4.3.3"
  - "@tailwindcss/oxide-linux-arm64-musl@4.3.3"
  - "@tailwindcss/oxide-linux-x64-gnu@4.3.3"
  - "@tailwindcss/oxide-linux-x64-musl@4.3.3"
  - "@tailwindcss/oxide-wasm32-wasi@4.3.3"
  - "@tailwindcss/oxide-win32-arm64-msvc@4.3.3"
  - "@tailwindcss/oxide-win32-x64-msvc@4.3.3"
  - "@tailwindcss/oxide@4.3.3"
  - "@tailwindcss/postcss@4.3.3"
  - tailwindcss@4.3.3
  - "@supabase/auth-js@2.110.7"
  - "@supabase/functions-js@2.110.7"
  - "@supabase/postgrest-js@2.110.7"
  - "@supabase/realtime-js@2.110.7"
  - "@supabase/storage-js@2.110.7"
  - "@supabase/supabase-js@2.110.7"
