-- Bind each signed fal.ai callback to the exact media-dispatch slot before
-- the provider request is sent. The opaque callback token is generated by the
-- application, only its SHA-256 digest is persisted, and a lost acknowledgement
-- can be replayed safely with the same digest before any provider spend.

alter table private.mvp_media_dispatches
  add column callback_token_sha256 text;

alter table private.mvp_media_dispatches
  add constraint mvp_media_dispatches_callback_token_sha256_check
  check (
    callback_token_sha256 is null
    or callback_token_sha256 ~ '^[a-f0-9]{64}$'
  );

create or replace function public.command_bind_mvp_media_dispatch_callback(
  p_dispatch_id uuid,
  p_expected_version bigint,
  p_claim_token uuid,
  p_fencing_token bigint,
  p_callback_token_sha256 text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare dispatch_row private.mvp_media_dispatches%rowtype;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_dispatch_id is null or p_expected_version is null
    or p_expected_version < 1 or p_claim_token is null
    or p_fencing_token is null or p_fencing_token < 1
    or p_callback_token_sha256 is null
    or p_callback_token_sha256 !~ '^[a-f0-9]{64}$'
  then
    raise exception 'media dispatch callback binding is invalid'
      using errcode = '22023';
  end if;

  select * into dispatch_row
  from private.mvp_media_dispatches
  where id = p_dispatch_id
  for update;
  if not found then
    raise exception 'media dispatch callback target is missing'
      using errcode = '40001';
  end if;
  if dispatch_row.state <> 'dispatching'
    or dispatch_row.version <> p_expected_version
    or dispatch_row.claim_token <> p_claim_token
    or dispatch_row.fencing_token <> p_fencing_token
    or dispatch_row.lease_expires_at <= statement_timestamp()
  then
    raise exception 'media dispatch callback binding fence is stale'
      using errcode = '40001';
  end if;
  if dispatch_row.callback_token_sha256 is not null
    and dispatch_row.callback_token_sha256 <> p_callback_token_sha256
  then
    raise exception 'media dispatch callback binding conflicts'
      using errcode = '40001';
  end if;

  if dispatch_row.callback_token_sha256 is null then
    update private.mvp_media_dispatches
    set callback_token_sha256 = p_callback_token_sha256
    where id = dispatch_row.id
    returning * into dispatch_row;
  end if;
  return to_jsonb(dispatch_row);
end;
$$;

revoke all on function public.command_bind_mvp_media_dispatch_callback(
  uuid,bigint,uuid,bigint,text
) from public, anon, authenticated;
grant execute on function public.command_bind_mvp_media_dispatch_callback(
  uuid,bigint,uuid,bigint,text
) to service_role;

revoke all on function public.command_reconcile_mvp_media_dispatch_webhook(
  uuid,text
) from public, anon, authenticated, service_role;
drop function public.command_reconcile_mvp_media_dispatch_webhook(uuid,text);

create function public.command_reconcile_mvp_media_dispatch_webhook(
  p_dispatch_id uuid,
  p_external_request_id text,
  p_callback_token text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  dispatch_row private.mvp_media_dispatches%rowtype;
  queue_base_url text;
begin
  if auth.role() is distinct from 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  if p_dispatch_id is null or p_external_request_id is null
    or p_external_request_id !~ '^[A-Za-z0-9_-]{6,200}$'
    or p_callback_token is null
    or p_callback_token !~ '^[A-Za-z0-9_-]{43}$'
  then
    raise exception 'media dispatch callback receipt is invalid'
      using errcode = '22023';
  end if;

  select * into dispatch_row
  from private.mvp_media_dispatches
  where id = p_dispatch_id
  for update;
  if not found then
    raise exception 'media dispatch callback target is missing'
      using errcode = '40001';
  end if;
  if dispatch_row.callback_token_sha256 is null
    or dispatch_row.callback_token_sha256 <>
      encode(extensions.digest(p_callback_token, 'sha256'), 'hex')
  then
    raise exception 'media dispatch callback binding does not match'
      using errcode = '40001';
  end if;
  if dispatch_row.state in ('submitted','succeeded') then
    if dispatch_row.external_request_id = p_external_request_id then
      return to_jsonb(dispatch_row);
    end if;
    raise exception 'media dispatch callback conflicts with committed receipt'
      using errcode = '40001';
  end if;
  if dispatch_row.state not in ('dispatching','outcome_unknown') then
    raise exception 'media dispatch callback state is not recoverable'
      using errcode = '40001';
  end if;

  queue_base_url := 'https://queue.fal.run/' || dispatch_row.endpoint
    || '/requests/' || p_external_request_id;
  update private.mvp_media_dispatches
  set state = 'submitted', version = version + 1,
      claim_token = null, lease_expires_at = null,
      external_request_id = p_external_request_id,
      status_url = queue_base_url || '/status',
      response_url = queue_base_url || '/response',
      dispatched_at = statement_timestamp(), completed_at = null,
      last_error_code = null, last_error_summary = null
  where id = dispatch_row.id
    and state in ('dispatching','outcome_unknown')
  returning * into dispatch_row;
  if not found then
    raise exception 'media dispatch callback reconciliation is stale'
      using errcode = '40001';
  end if;
  return to_jsonb(dispatch_row);
end;
$$;

revoke all on function public.command_reconcile_mvp_media_dispatch_webhook(
  uuid,text,text
) from public, anon, authenticated;
grant execute on function public.command_reconcile_mvp_media_dispatch_webhook(
  uuid,text,text
) to service_role;
